expbooster: true
mobdropbooster: true
sheepshearingbooster: true
shopbooster: true
speedbooster: true
mcmmo-miningbooster: true
mcmmo-woodcuttingbooster: true
mcmmo-herbalismbooster: true
mcmmo-fishingbooster: true
mcmmo-excavationbooster: true
mcmmo-unarmedbooster: true
mcmmo-archerybooster: true
mcmmo-swordsbooster: true
mcmmo-axesbooster: true
mcmmo-repairbooster: true
mcmmo-acrobaticsbooster: true
mcmmo-alchemybooster: true
mcmmo-pilotingbooster: false
mcmmo-salvagebooster: true
mcmmo-smeltingbooster: true
mcmmo-tamingbooster: true

#entities that are effected by the mobdropbooster
entities:
  - Cow
  - Pig
  - Sheep
  - Chicken
  - Enderman
  - Zombie
  - Skeleton
  - Creeper
# - Armor Stand
# - Arrow
# - Bat
  - Blaze
# - Boat
  - Cave Spider
# - Complex Part
# - Dropped Item
# - Egg
# - Ender Crystal
# - Ender Dragon
# - Ender Pearl
# - Ender Signal
# - Endermite
# - Experience Orb
# - Falling Block
# - Fireball
# - Firework
# - Fishing hook
# - Giant
  - Ghast
  - Guardian
# - EntityHorse
# - Iron Golem
# - Item Frame
# - Leash Hitch
# - Lighting
  - Magma Cube
# - Minecart
# - Minecart Chest
# - Minecart Furnace
# - Minecart Command
# - Minecart Hopper
# - Minecart Mob Spawner
# - Minecart Tnt
# - Mushroom Cow
# - Ocelot
# - Painting
  - Pig Zombie
# - Player
# - Primed TNT
  - Rabbit
# - Silverfish
  - Slime
# - Snowman
  - Spider
# - Splash Potion
  - Sqiud
# - Thrown Exp Bottler
# - Unkown
# - Villager
# - Weather
  - Witch
# - Wither
# - Wither Skull
  - Wolf