name: SQBoosters
main: com.ginger_walnut.sqboosters.SQBoosters
version: 1.2
description: A plugin that adds various boosters
depend: [Movecraft]
commands:
   expboost:
      description: Manages SQExpBoost
   mobdropboost:
      description: Manages SQMobDropBoost
   sheepshearboost:
      description: Manages SQSheepShearBoost
   shopboost:
      description: Manages SQShopBoost
   speedboost:
      description: Manages SQSpeedBoost
   mcmmo-miningboost:
      description: Manages SQMMO-MiningBoost
   mcmmo-woodcuttingboost:
     description: Manages SQMMO-WoodcuttingBoost
   mcmmo-herbalismboost:
     description: Manages SQMMO-HerbalismBoost
   mcmmo-fishingboost:
     description: Manages SQMMO-FishingBoost
   mcmmo-excavationboost:
     description: Manages SQMMO-ExcavationBoost
   mcmmo-unarmedboost:
     description: Manages SQMMO-UnarmedBoost
   mcmmo-archeryboost:
     description: Manages SQMMO-ArcheryBoost
   mcmmo-swordsboost:
     description: Manages SQMMO-SwordsBoost
   mcmmo-axesboost:
     description: Manages SQMMO-AxesBoost
   mcmmo-repairboost:
     description: Manages SQMMO-RepairBoost
   mcmmo-acrobaticsboost:
     description: Manages SQMMO-AcrobaticsBoost
   mcmmo-alchemyboost:
     description: Manages SQMMO-AlchemyBoost
   mcmmo-pilotingboost:
     description: Manages SQMMO-PilotingBoost
   mcmmo-salvageboost:
     description: Manages SQMMO-SalvageBoost
   mcmmo-smeltingboost:
     description: Manages SQMMO-SmeltingBoost
   mcmmo-tamingboost:
     description: Manages SQMMO-TamingBoost

   thank:
      description: Thanks a player for purchasing a booster with credits

   booster:
   boosters:

permissions:
   SQBoosters.viewHelp:
      description: Premission node for viewing help
      default: op
   SQBoosters.addMultiplier:
      description: Premission node for adding a multipier
      default: op